### PR TITLE
Respect `retry-after` header and allow for separate max number of attempts for rate limits in `retry`

### PR DESCRIPTION
**Pull request by DerJacques**
When the existing `retry` function is given a `maxNumAttempts`, the limit applies to rate limits as well.
This may not desired, as business or network errors usually should be retried less often than rate limits.

The new implementation also respects the `retry-after` header, in an attempt to reduce the rate at which requests are sent to Zendesk.

**Please note that this is technically a breaking change**
If consumers have defined a `maxNumAttempts` this change will now ignore that value if the given error is a rate limit error.
I decided to set a default value of `20` to make sure that retries don't happen indefinitely.

### CODE REVIEW

**Review by emattson — APPROVED** [review]
LGTM

**Review by e10jc — CHANGES_REQUESTED** [review]
I really like this direction but I'm confused about the new arg `maxNumAttemptsOnRateLimit`. I mean, I think `maxNumAttempts` was designed specifically for rate limit errors -- why else would you want to retry a call?

**Comment by DerJacques** [comment]
@e10jc Oh I see, that actually explains some questions about the current implementation!

I would argue that multiple errors should be "retriable" (on top of rate limit errors): Network errors, Zendesk Database errors, and weird HTTP 500ish errors, all of which we regularly see returned by the Zendesk API.

Of course my proposed change may be a problem, if current consumers set `maxNumAttempts` with the expectation that it only applies to rate limits.

How would you feel about a solution where we mark the following "known" errors as non-retriable?
`BadRequestError`, `Authentication`, `Permission`, `NotFound`, `Unprocessable`.

Then we could stick to only use `maxNumAttempts`, but it would apply to both rate limit errors and network errors or other "unknown" errors.

The only downside I see with not splitting up `maxNumAttempts` and `maxNumAttemptsOnRateLimit` is that consumers may want to retry rate limit errors indefinitely (or at least a high number of times), but only want network errors to be retried a handful of times.

What do you think?

**Comment by e10jc** [comment]
@DerJacques I like the idea of respecting the `retry-after` header, but I don't like the idea of retrying arbitrary Zendesk errors as a common practice: if a `POST` or `PUT` call fails for no good reason, it still might have produced a state change on the Zendesk side that would get worse upon retry.

So I think perhaps we should rewind the conversation a bit and I'll ask: what problem is this PR attempting to solve?

**Comment by DerJacques** [comment]
@e10jc I totally get that.

The issue I'm trying to solve is that we sometimes run long jobs in the Bulk Mailer that make many, many requests (e.g. when building a list of receivers for a bulk mailer). Sometimes these requests fail for strange reasons. Here's an example: 

https://app.datadoghq.com/logs?query=name%3Abulk-api-production-v2%20%40tags%3AAddTagsToUsersBulkJob%20status%3Awarn&cols=host%2C%40type%2Cecs_container_name%2C%40tags&event=AQAAAYJqa5lARbQpLwAAAABBWUpxYTZpcUFBQ1E5Vk5odnMwY2JBQUU&index=&messageDisplay=inline&saved-view-id=119834&stream_sort=time%2Casc&viz=stream&from_ts=1659639911185&to_ts=1660244711185&live=true

It seems like what we end up doing in most situations is running the full job again, even though a simple retry of the specific request would likely have solved the issue.

How about we proceed with something like this:
1. We respect the `retry-after` header on RateLimit errors (this alone would be a huge help)
2. We add a flag such as `retryOnAllErrorTypes` to allow consumers to opt in to this behavior.
3. We remove the `maxNumAttemptsOnRateLimit` and stick with `maxNumAttempts` for simplicity.

**Comment by e10jc** [comment]
@DerJacques Ah shoot Zendesk still has those damn database errors? I thought they had gone away over time. I guess the team has just done a good job at going around them lol.

Okay so:
1. Yes. Let's definitely do that.
2. I like this. Alternatively we could add a new arg with a default like `errorTypesToRetry?: (RateLimit | BadRequestError)[] = [RateLimit]` so that way consumers could get granular if they want, but the default behavior would remain the same.
3. Agreed.

**Comment by DerJacques** [comment]
@e10jc That sounds like a plan! Will implement :)

**Comment by DerJacques** [comment]
@e10jc I think this is ready for another round!

I did the following:
1. Rate limits are retried by default and respect the `retry-after` header.
2. The consumer can provide a list of errors that should be retried. There's a special option called `'all'` that will retry _any_ error (network error, API error, etc).
3. I introduced a fallback error called `UnknownApiError` that can be included in the list of errors to retry.
4. All known errors except for `UnknownApiError` and `RateLimit` are not marked as retriable. I don't see a scenario where e.g. bad input or authorization errors would disappear on a second try.

I hope you agree with the decisions and implementations, but please let me know if you do not.

**Comment by DerJacques** [comment]
@e10jc How are you feeling about this? :)

**Review by e10jc — APPROVED** [review]
Ah this seems lovely! I'll take it from here: I want to look at it locally, and then I'll publish a new version to npm.

**Pull request merged**
